# Version of docker-compose
version: "3.7"

# Declaring the services, i.e, the containers
services:

# Declaring a container and its build location, port, working directory and the volumes it will be mapped inside the container.
  carsint:
      build: ./services/carsInt/
      command: node index.js
      ports:
        - 3000:3000
      working_dir: /app
      volumes:
        - ./services/carsInt/:/app
  
# Declaring a container and its build location, port, working directory and the volumes it will be mapped inside the container. 
  carsext:
      build: ./services/carsExt/
      command: node index.js
      ports:
        - 3001:3001
      working_dir: /app
      volumes:
        - ./services/carsExt/:/app
        

