# Pulling the latest node images from dockerhub
FROM node:latest

# The working directory inside the container
WORKDIR /app/

# Copying all the directories and files from its present location inside conatainer home directory.
COPY . .

# Running this command to install all the dependencies inside the container
RUN npm install



